run:
  # modules-download-mode: vendor
  tests: true
  timeout: 1m

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - forbidigo # we need to use fmt.Print*()
    - gomnd
    - nolintlint
    - paralleltest # tests only take 2.5s to run. no need to parallelize
    - testpackage
    - wsl

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 10
  gofmt:
    simplify: true
