run:
  modules-download-mode: vendor
  tests: true
  timeout: 1m

linters:
  enable-all: true
  disable:
    - depguard # enforces that only deps on a whitelist can be used (meant for orgs, not small projects)
    - execinquery # deprecated
    - exhaustruct
    - exportloopref # deprecated
    - forbidigo # we need to use fmt.Print*()
    - gomnd
    - govet # we run the official go vet separately
    - nolintlint # we do occasionally need to suppress linter false positives
    - nonamedreturns # named returns often help readability
    - paralleltest # tests only take 2.5s to run. no need to parallelize
    - staticcheck # dominickh doesn't recommend running staticcheck as part of golangci-lint, so we run Real Staticcheck™ separately
    - testpackage
    - varnamelen # makes bad suggestions
    - wsl

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 10
  gofumpt:
    extra-rules: true
