run:
  modules-download-mode: vendor
  tests: true
  timeout: 1m

linters:
  enable-all: true
  disable:
    - depguard # enforces that only deps on a whitelist can be used (meant for orgs, not small projects)
    - execinquery # deprecated
    - exhaustruct
    - forbidigo # we need to use fmt.Print*()
    - gomnd
    - nolintlint
    - nonamedreturns
    - paralleltest # tests only take 2.5s to run. no need to parallelize
    - testpackage
    - varnamelen # makes bad suggestions
    - wsl

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 10
  gofumpt:
    extra-rules: true
