run:
  modules-download-mode: vendor
  tests: true
  timeout: 1m

linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - gomnd
    - testpackage
    - nolintlint
    - wsl

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - opinionated
      - performance
      - style
    disabled-checks:
      - whyNoLint
  gocyclo:
    min-complexity: 11
  gofmt:
    simplify: true
