version: 2.1

executors:
  go-container:
    docker:
      - image: golang:1.18
    working_directory: /go/src/q

jobs:
  lint:
    docker:
      - image: golangci/golangci-lint:v1.46-alpine
    steps:
      - checkout
      - run: golangci-lint run
  test:
    executor:
      name: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkgs-{{ checksum "go.sum" }}
      - run: go test -v -race ./...
      - save_cache: # cache the /go/pkg directory
          key: go-pkgs-{{ checksum "go.sum" }}
          paths:
            - /go/pkg

workflows:
  build_and_test:
    jobs:
      - lint
      - test
