version: 2.1

executors:
  go-container:
    docker:
      - image: golang:1.13
    environment:
      GO111MODULE: "on"
      GOFLAGS: "-mod=vendor"
    working_directory: /go/src/github.com/y0ssar1an/q

jobs:
  lint:
    executor:
      name: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkgs-{{ checksum "go.sum" }}
      - run: GO111MODULE=off go get github.com/golangci/golangci-lint/cmd/golangci-lint
      - run: golangci-lint run
  test:
    executor:
      name: go-container
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-pkgs-{{ checksum "go.sum" }}
      - run: go test -v -race ./...
      - save_cache: # cache the /go/pkg directory
          key: go-pkgs-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg"

workflows:
  build_and_test:
    jobs:
      - lint
      - test
