name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: set up go
        uses: actions/setup-go@v6 # TODO: replace with WillAbides/setup-go-faster@v1 when it's fixed
        with:
          go-version-file: go.mod
      - name: lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: latest

  check:
    name: go vet and staticcheck
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: set up go
        uses: actions/setup-go@v6 # TODO: replace with WillAbides/setup-go-faster@v1 when it's fixed
        with:
          go-version-file: go.mod
      - name: run go vet
        run: go vet ./...
      - name: run staticcheck
        uses: dominikh/staticcheck-action@v1
        with:
          # uses setup-go-faster by default, which is currently failing,
          # so we disable automatic installation of Go and install Go
          # ourselves with setup-go
          install-go: false

  test:
    name: unit tests with race detector enabled
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - name: set up go
        uses: actions/setup-go@v6 # TODO: replace with WillAbides/setup-go-faster@v1 when it's fixed
        with:
          go-version-file: go.mod
      - name: run unit tests
        run: go test -v -race ./...
